[workspace]
members = ["projects/*"]
default-members = [
    "projects/diffuser-load",
]
exclude = [
    "projects/.DS_Store",
    "projects/diffuser-pack"
]

[profile.release]
lto = true
panic = "abort"
